### ISSUE TITLE
Running Openwebrtc Daemon in Linux

### ISSUE THREAD

**Issue by SrujithPoondla** [danielwegener/openwebrtc-java#1]
The build of openwebrtc had done successfully by following the instruction from [https://github.com/EricssonResearch/openwebrtc/wiki/Building-OpenWebRTC]. After that I tried running Daemon but it is giving the error like this 

```
srujith@srujith-HP-ENVY-dv6-Notebook-PC:~/cerbero/sources/linux_x86_64/openwebrtc-0.3.0/bridge$ ./openwebrtc-daemon 

** (gst-plugin-scanner:2784): CRITICAL **: Couldn't g_module_open libpython. Reason: /usr/lib/libpython2.7.so: cannot open shared object file: No such file or directory
{"line":24,"column":32,"sourceURL":"/opt/openwebrtc-0.3/share/seed-gtk3/extensions/Seed.js"}

``
```

**Comment by danielwegener** [comment]
I have not tried to run the deamon yet, actually you may dont need it,  the OWRBridge is selfcontained

**Comment by SrujithPoondla** [comment]
Issue resolved
